### ISSUE TITLE
hingeABL替换ATL后，效果不好。

### ISSUE THREAD

**Issue by Deargoodnight** [Jize-W/HingeABL#2]

**Comment by Jize-W** [comment]
Hello, could you please provide detailed information about your experiments, such as the RE method, and the dataset you use?

**Comment by Deargoodnight** [comment]
the dataset chosen is DocRED, and the baseline model is the ATLOP。

**Comment by Jize-W** [comment]
It is recommended to conduct experiments on Re-DocRED, since the annotation of DocRED is incomplete, which may cause the overwhelming false negative problem and lead to an unfair evaluation in the DocRED dataset. Please refer to https://arxiv.org/abs/2205.12696.

**Comment by Jize-W** [comment]
如果仍有疑问，欢迎进一步讨论。
